try{
    f1();
}catch(error){
    console.log(error);

}
finally{
    console.log("This will execute")
}
